services:
  # Elasticsearch - Armazenamento de logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: gwan-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-GwanLogs2024!}
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
      - ingest.geoip.downloader.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - gwan
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 300s
      timeout: 120s
      retries: 2
      start_period: 900s
    # Configurações de recursos para produção
    # Limite de memória: 3GB
    # Reserva de memória: 1GB

  # Logstash - Processamento de logs
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    container_name: gwan-logstash
    environment:
      - ELASTICSEARCH_HOSTS=${LOGSTASH_ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
      - ELASTICSEARCH_USERNAME=${LOGSTASH_ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${LOGSTASH_ELASTICSEARCH_PASSWORD:-GwanLogs2024!}
      - LS_JAVA_OPTS=-Xms512m -Xmx1g
    volumes:
      - ls_data:/usr/share/logstash/data
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./configs/logstash/pipelines:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - gwan
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 300s
      timeout: 120s
      retries: 3
      start_period: 600s
    # Configurações de recursos para produção
    # Limite de memória: 1.5GB
    # Reserva de memória: 512MB

  # Kibana - Interface de visualização
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: gwan-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SSL_VERIFY=false
      - SERVER_NAME=gwan-kibana
      - SERVER_HOST=0.0.0.0
    volumes:
      - kb_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - gwan
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 300s
      timeout: 120s
      retries: 3
      start_period: 1200s
    # Configurações de recursos para produção
    # Limite de memória: 1GB
    # Reserva de memória: 512MB

  # OpenTelemetry Collector - Coleta de telemetria
  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: gwan-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
    networks:
      - gwan
    depends_on:
      - elasticsearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:13133/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configurações de recursos para produção
    # Limite de memória: 512MB
    # Reserva de memória: 256MB

  # Jaeger - Visualização de traces
  jaeger:
    image: jaegertracing/all-in-one:1.55.0
    container_name: gwan-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_ENDPOINT=0.0.0.0:4317
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"  # UDP collector
    networks:
      - gwan
    depends_on:
      - otel-collector
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:16686/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configurações de recursos para produção
    # Limite de memória: 512MB
    # Reserva de memória: 256MB

  # Prometheus - Coleta de métricas
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: gwan-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    volumes:
      - prometheus_data:/prometheus
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - gwan
    depends_on:
      - otel-collector
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configurações de recursos para produção
    # Limite de memória: 512MB
    # Reserva de memória: 256MB

  # Alertmanager - Gerenciamento de alertas
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: gwan-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager_data:/alertmanager
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - gwan
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9093/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configurações de recursos para produção
    # Limite de memória: 256MB
    # Reserva de memória: 128MB

volumes:
  es_data:
    driver: local
  kb_data:
    driver: local
  ls_data:
    driver: local
  prometheus_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  gwan:
    external: true
